package io.sigcorr.correlation.engine;

import io.sigcorr.core.event.SignalingEvent;
import io.sigcorr.core.identity.IdentityResolver;
import io.sigcorr.core.identity.SubscriberIdentity;
import io.sigcorr.core.model.SignalingOperation;
import io.sigcorr.correlation.window.TemporalWindow;
import io.sigcorr.detection.patterns.AttackPattern;
import io.sigcorr.detection.patterns.AttackPatternCatalog;
import io.sigcorr.detection.rules.PatternMatcher;
import io.sigcorr.detection.scoring.SecurityAlert;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.Duration;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.CopyOnWriteArrayList;

/**
 * The main correlation engine — the heart of SigCorr.
 *
 * Orchestrates the full pipeline:
 * 1. Receives normalized SignalingEvents from protocol decoders
 * 2. Resolves subscriber identity (IMSI ↔ MSISDN mapping)
 * 3. Places events into the temporal correlation window
 * 4. Runs pattern matching against all known attack patterns
 * 5. Emits SecurityAlerts for confirmed matches
 *
 * The engine is designed for batch processing of pcap/trace files,
 * not real-time streaming (though the architecture supports it).
 *
 * Thread-safe: can accept events from multiple decoder threads.
 */
public class CorrelationEngine {

    private static final Logger log = LoggerFactory.getLogger(CorrelationEngine.class);

    private final IdentityResolver identityResolver;
    private final TemporalWindow temporalWindow;
    private final PatternMatcher patternMatcher;
    private final List<SecurityAlert> alerts;
    private final EngineConfig config;

    // Statistics
    private long eventsProcessed = 0;
    private long eventsDropped = 0;
    private final Map<String, Long> eventsByInterface = new LinkedHashMap<>();

    public CorrelationEngine(EngineConfig config) {
        this.config = Objects.requireNonNull(config);
        this.identityResolver = new IdentityResolver();
        this.temporalWindow = new TemporalWindow(config.getCorrelationWindow());

        List<AttackPattern> patterns = config.getCustomPatterns() != null
                ? config.getCustomPatterns()
                : AttackPatternCatalog.getAllPatterns();
        this.patternMatcher = new PatternMatcher(patterns);
        this.alerts = new CopyOnWriteArrayList<>();
    }

    /**
     * Create engine with default configuration.
     */
    public static CorrelationEngine createDefault() {
        return new CorrelationEngine(EngineConfig.defaults());
    }

    /**
     * Process a single signaling event through the correlation pipeline.
     *
     * @param event normalized signaling event from a protocol decoder
     * @return any alerts generated by this event (may be empty)
     */
    public List<SecurityAlert> processEvent(SignalingEvent event) {
        Objects.requireNonNull(event, "event must not be null");

        eventsProcessed++;
        String ifaceName = event.getProtocolInterface().getDisplayName();
        eventsByInterface.merge(ifaceName, 1L, Long::sum);

        // Step 1: Learn identity mappings from signaling
        // Capture the mapping count before learning to detect new mappings
        int mappingsBefore = identityResolver.getMappingCount();
        learnIdentityMappings(event);
        boolean newMappingLearned = identityResolver.getMappingCount() > mappingsBefore;

        // Step 2: Resolve correlation key
        String correlationKey = identityResolver.getCorrelationKey(event.getSubscriber());

        // Step 2b: If we learned a new IMSI↔MSISDN mapping, re-index events
        // that were previously stored under the MSISDN key to the IMSI key.
        // This is critical: SRI request is indexed by MSISDN, SRI response reveals
        // the IMSI, and PSI uses the IMSI. Without re-indexing, the SRI request
        // is in a different bucket than the PSI and the attack chain is invisible.
        if (newMappingLearned) {
            reindexEventsForMapping(event, correlationKey);
        }

        // Step 3: Add to temporal window
        temporalWindow.addEvent(correlationKey, event);

        // Step 4: Run pattern matching for this subscriber
        List<SignalingEvent> subscriberTimeline = temporalWindow.getAllEvents(correlationKey);
        List<SecurityAlert> newAlerts = patternMatcher.matchAll(correlationKey, subscriberTimeline);

        // Step 5: Deduplicate alerts (same pattern + subscriber within window)
        List<SecurityAlert> deduplicated = deduplicateAlerts(newAlerts);

        alerts.addAll(deduplicated);

        if (!deduplicated.isEmpty()) {
            for (SecurityAlert alert : deduplicated) {
                log.warn("ALERT: {}", alert);
            }
        }

        return deduplicated;
    }

    /**
     * When we learn a new IMSI-MSISDN mapping, move any events that were stored
     * under the old MSISDN key to the canonical IMSI key. Without this, events
     * that arrived before the mapping was known would be stranded in a separate
     * bucket and never correlate with later events that use the IMSI.
     */
    private void reindexEventsForMapping(SignalingEvent triggeringEvent, String canonicalKey) {
        String msisdn = triggeringEvent.getParameter("msisdn");
        String imsi = triggeringEvent.getParameter("imsi");

        // Build list of alternative keys that might hold orphaned events
        List<String> altKeys = new ArrayList<>();
        if (msisdn != null) altKeys.add("MSISDN:" + msisdn);
        if (imsi != null) altKeys.add("IMSI:" + imsi);

        // Also check resolved mappings
        if (msisdn != null) {
            identityResolver.lookupImsi(msisdn).ifPresent(i -> altKeys.add("IMSI:" + i));
        }
        if (imsi != null) {
            identityResolver.lookupMsisdn(imsi).ifPresent(m -> altKeys.add("MSISDN:" + m));
        }

        for (String altKey : altKeys) {
            if (!altKey.equals(canonicalKey)) {
                List<SignalingEvent> oldEvents = temporalWindow.getAllEvents(altKey);
                if (!oldEvents.isEmpty()) {
                    log.debug("Re-indexing {} events from {} to {}", oldEvents.size(), altKey, canonicalKey);
                    for (SignalingEvent oldEvent : oldEvents) {
                        temporalWindow.addEvent(canonicalKey, oldEvent);
                    }
                }
            }
        }
    }

    /**
     * Process a batch of events (e.g., from a pcap file).
     * Events should be in chronological order.
     *
     * @param events list of normalized events, chronologically ordered
     * @return all alerts generated
     */
    public List<SecurityAlert> processBatch(List<SignalingEvent> events) {
        List<SecurityAlert> batchAlerts = new ArrayList<>();

        for (SignalingEvent event : events) {
            List<SecurityAlert> eventAlerts = processEvent(event);
            batchAlerts.addAll(eventAlerts);
        }

        log.info("Batch complete: {} events processed, {} alerts generated",
                events.size(), batchAlerts.size());

        return batchAlerts;
    }

    /**
     * Learn IMSI ↔ MSISDN mappings from observed signaling.
     *
     * Key learning opportunities:
     * - MAP SendRoutingInfo: request has MSISDN, response has IMSI
     * - MAP UpdateLocation: has IMSI
     * - GTP-C Create-Session: may have both IMSI and MSISDN
     * - Diameter S6a: User-Name contains IMSI
     */
    private void learnIdentityMappings(SignalingEvent event) {
        String imsi = event.getParameter("imsi");
        String msisdn = event.getParameter("msisdn");

        if (imsi != null && msisdn != null) {
            identityResolver.registerMapping(imsi, msisdn);
            log.debug("Learned identity mapping: IMSI={} ↔ MSISDN={} from {}",
                    imsi, msisdn, event.getOperation().getDisplayName());
        }

        // Also update subscriber identity with resolved info
        if (imsi != null && event.getSubscriber().hasMsisdn() && !event.getSubscriber().hasImsi()) {
            String existingMsisdn = event.getSubscriber().getMsisdn().orElse(null);
            if (existingMsisdn != null) {
                identityResolver.registerMapping(imsi, existingMsisdn);
            }
        }
    }

    /**
     * Deduplicate alerts: same pattern + subscriber within a short window
     * should not generate multiple alerts.
     */
    private List<SecurityAlert> deduplicateAlerts(List<SecurityAlert> newAlerts) {
        List<SecurityAlert> unique = new ArrayList<>();

        for (SecurityAlert newAlert : newAlerts) {
            boolean isDuplicate = alerts.stream().anyMatch(existing ->
                    existing.getMatchedPattern().getPatternId()
                            .equals(newAlert.getMatchedPattern().getPatternId())
                            && existing.getSubscriberKey().equals(newAlert.getSubscriberKey())
                            && Math.abs(existing.getDetectionTime().toEpochMilli()
                            - newAlert.getDetectionTime().toEpochMilli()) < config.getDeduplicationWindowMs()
            );

            if (!isDuplicate) {
                unique.add(newAlert);
            }
        }

        return unique;
    }

    // === Accessors ===

    public List<SecurityAlert> getAlerts() {
        return Collections.unmodifiableList(alerts);
    }

    public List<SecurityAlert> getAlertsBySeverity(AttackPattern.Severity minSeverity) {
        return alerts.stream()
                .filter(a -> a.getSeverity().getLevel() >= minSeverity.getLevel())
                .toList();
    }

    public List<SecurityAlert> getAlertsForSubscriber(String subscriberKey) {
        return alerts.stream()
                .filter(a -> a.getSubscriberKey().equals(subscriberKey))
                .toList();
    }

    public List<SecurityAlert> getCrossProtocolAlerts() {
        return alerts.stream()
                .filter(SecurityAlert::isCrossProtocol)
                .toList();
    }

    public IdentityResolver getIdentityResolver() { return identityResolver; }
    public TemporalWindow getTemporalWindow() { return temporalWindow; }
    public long getEventsProcessed() { return eventsProcessed; }
    public long getEventsDropped() { return eventsDropped; }
    public Map<String, Long> getEventsByInterface() { return Collections.unmodifiableMap(eventsByInterface); }

    /**
     * Generate a summary report of the analysis.
     */
    public AnalysisSummary getSummary() {
        return new AnalysisSummary(
                eventsProcessed,
                eventsDropped,
                new LinkedHashMap<>(eventsByInterface),
                temporalWindow.getSubscriberCount(),
                identityResolver.getMappingCount(),
                alerts.size(),
                getCrossProtocolAlerts().size(),
                getAlertsBySeverity(AttackPattern.Severity.CRITICAL).size(),
                getAlertsBySeverity(AttackPattern.Severity.HIGH).size()
        );
    }

    /**
     * Reset engine state.
     */
    public void reset() {
        identityResolver.clear();
        temporalWindow.clear();
        alerts.clear();
        eventsProcessed = 0;
        eventsDropped = 0;
        eventsByInterface.clear();
    }

    /**
     * Summary of analysis results.
     */
    public record AnalysisSummary(
            long totalEvents,
            long droppedEvents,
            Map<String, Long> eventsByInterface,
            int subscribersTracked,
            int identityMappings,
            int totalAlerts,
            int crossProtocolAlerts,
            int criticalAlerts,
            int highAlerts
    ) {
        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append("═══════════════════════════════════════════════\n");
            sb.append("  SigCorr Analysis Summary\n");
            sb.append("═══════════════════════════════════════════════\n");
            sb.append(String.format("  Events processed:      %,d\n", totalEvents));
            sb.append(String.format("  Events dropped:        %,d\n", droppedEvents));
            sb.append(String.format("  Subscribers tracked:   %,d\n", subscribersTracked));
            sb.append(String.format("  Identity mappings:     %,d\n", identityMappings));
            sb.append("───────────────────────────────────────────────\n");
            sb.append("  Events by Interface:\n");
            eventsByInterface.forEach((iface, count) ->
                    sb.append(String.format("    %-20s %,d\n", iface, count)));
            sb.append("───────────────────────────────────────────────\n");
            sb.append(String.format("  Total alerts:          %,d\n", totalAlerts));
            sb.append(String.format("  Cross-protocol alerts: %,d\n", crossProtocolAlerts));
            sb.append(String.format("  Critical severity:     %,d\n", criticalAlerts));
            sb.append(String.format("  High severity:         %,d\n", highAlerts));
            sb.append("═══════════════════════════════════════════════\n");
            return sb.toString();
        }
    }
}
